spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:auth-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0
  servlet:
    context-path: /auth
